name: Generate md5 sums
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'false'
          remove-dotnet: 'false'
          remove-haskell: 'false'

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache ISO
        uses: actions/cache@v3
        id: cache-iso
        with:
          path: ${{ github.workspace }}/Downloads
          key: kubuntu-iso-24.10
          
      - name: Download ISO if not cached
        if: ${{ steps.cache-iso.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p ${{ github.workspace }}/Downloads
          curl -L -o ${{ github.workspace }}/Downloads/kubuntu-24.04-desktop-amd64.iso \
               https://cdimage.ubuntu.com/kubuntu/releases/24.04/release/kubuntu-24.04-desktop-amd64.iso

      - name: Run build script
        run: |
          chmod +x ${{ github.workspace }}/build_in_docker.sh
          ${{ github.workspace }}/build_in_docker.sh

      - name: Copy generated ISO to workspace
        run: |
          cp ${{ github.workspace }}/output/*.iso ${{ github.workspace }}

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kubuntu
          path: ${{ github.workspace }}/*.iso

